language: php
php:
  - 7.3

install:
  - composer update

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter env
  - ./cc-test-reporter before-build
  - mkdir -p coverage

script:
  - composer test:coverage

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
